alias cdh='cd $HOME/projects/HASKELL'
alias logoutall='pkill -u $(whoami)'
alias cat='bat -pp'
alias pull-system='(cd /etc/nixos; sudo git fetch; sudo git pull)'
alias pull-user='(cd $HOME/.config/home-manager; git fetch; git pull $HOME/.config/home-manager)'
function update-system(){ sudo nixos-rebuild switch --update-input nixpkgs --flake /etc/nixos#"$1"; }
alias update-user='home-manager switch --update-input nixpkgs --update-input steamappidlist'
alias cd='z'
